name: Generate Client

on:
    workflow_dispatch:

jobs:
    generate-client:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: "Install Poetry"
                run: "pipx install poetry"
            -   name: Install OpenAPI Python Generator
                run: "pipx install openapi-python-client"
            -   name: Set up Python ${{matrix.python-version}}
                uses: "actions/setup-python@v5"
                with:
                    python-version: 3.11
                    cache: poetry
            -   name: Install jq
                run: |
                    sudo apt-get update
                    sudo apt-get install -y jq
            -   name: Download OpenAPI schema and update pyproject.toml
                run: |
                    curl -LJO https://raw.githubusercontent.com/Qwizi/cs2-battle-bot-api/feature/src/openapi.json
                    VERSION=$(jq -r .info.version openapi.json)
                    sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
                    echo "Updated version to $VERSION"
            -   name: Generate Python client
                run: "cd .. && openapi-python-client update --path cs2-battle-bot-api-client/openapi.json && echo ls"